# Défi des parties 4 et 5

## Numpy

In [1]:
import numpy as np

- Créer un tableau de zéros de dimensions (5, 8, 6)

In [2]:
tab_1 = np.zeros((5, 8, 6))
print(tab_1)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


- Créer un tableau de dimensions (4, 3, 6, 8) à l'aide des fonctions np.arange() et reshape(). Transformer le tableau en un vecteur

In [3]:
tab_2 = np.arange(576).reshape(4, 3, 6, 8)
print(tab_2)
tab_3 = tab_2.ravel()
print(tab_3)

[[[[  0   1   2   3   4   5   6   7]
   [  8   9  10  11  12  13  14  15]
   [ 16  17  18  19  20  21  22  23]
   [ 24  25  26  27  28  29  30  31]
   [ 32  33  34  35  36  37  38  39]
   [ 40  41  42  43  44  45  46  47]]

  [[ 48  49  50  51  52  53  54  55]
   [ 56  57  58  59  60  61  62  63]
   [ 64  65  66  67  68  69  70  71]
   [ 72  73  74  75  76  77  78  79]
   [ 80  81  82  83  84  85  86  87]
   [ 88  89  90  91  92  93  94  95]]

  [[ 96  97  98  99 100 101 102 103]
   [104 105 106 107 108 109 110 111]
   [112 113 114 115 116 117 118 119]
   [120 121 122 123 124 125 126 127]
   [128 129 130 131 132 133 134 135]
   [136 137 138 139 140 141 142 143]]]


 [[[144 145 146 147 148 149 150 151]
   [152 153 154 155 156 157 158 159]
   [160 161 162 163 164 165 166 167]
   [168 169 170 171 172 173 174 175]
   [176 177 178 179 180 181 182 183]
   [184 185 186 187 188 189 190 191]]

  [[192 193 194 195 196 197 198 199]
   [200 201 202 203 204 205 206 207]
   [208 209 210 211 212 213 

- Créer une tableau de dimension (5, 8) avec des valeurs aléatoires comprises entre 1 et 12. Sélectionner uniquement les valeurs supérieures à 5. Remplacer toutes les valeurs 10 par np.Nan

In [4]:
tab_4 = np.random.randint(1, 13, (5, 8))
print(tab_4)
tab_5 = tab_4[tab_4 > 5]
print(tab_5)
tab_6 = np.where(tab_5==10, np.nan, tab_5)
print(tab_6)

[[ 1  1  9 12  2  7  5  4]
 [11  3  5  1  7  5  3 10]
 [ 4  6  7  1 10  8  2  1]
 [ 6  8  8  1  4  8  4  5]
 [ 9  6  5  7  5  9  4  6]]
[ 9 12  7 11  7 10  6  7 10  8  6  8  8  8  9  6  7  9  6]
[ 9. 12.  7. 11.  7. nan  6.  7. nan  8.  6.  8.  8.  8.  9.  6.  7.  9.
  6.]


## Pandas

In [5]:
import pandas as pd

- Créer un dataframe pandas à partir du dictionnaire suivant : {'X':[7,8,9,8,5], 'Y':[4,9,8,3,6],'Z':[6,7,9,2,3]}. Créer un nouveau dataframe avec le carré de la première colonne, le cube de la deuxième colonne et la puissance quatre de la troisième colonne. Concaténer les deux dataframes horizontalement

In [6]:
data = {
    'X':[7,8,9,8,5],
    'Y':[4,9,8,3,6],
    'Z':[6,7,9,2,3],
}
df = pd.DataFrame(data)
print(df)
df_234 = pd.concat([df['X']**2, df['Y']**3, df['Z']**4], axis=1)
print(df_234)
df_concat = pd.concat([df, df_234], axis="columns")
df_concat.columns = ("A","B","C","D","E","F")
print(df_concat)

   X  Y  Z
0  7  4  6
1  8  9  7
2  9  8  9
3  8  3  2
4  5  6  3
    X    Y     Z
0  49   64  1296
1  64  729  2401
2  81  512  6561
3  64   27    16
4  25  216    81
   A  B  C   D    E     F
0  7  4  6  49   64  1296
1  8  9  7  64  729  2401
2  9  8  9  81  512  6561
3  8  3  2  64   27    16
4  5  6  3  25  216    81


- Créer un dataframe à partir du dictionnaire suivant : {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, 15, 9, 20, 14.5, 7, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]}. Récupérer les noms des personnes au dessus de la moyenne (la moyenne est calculée avec le nombre d'essais)

In [7]:
data = {
    'name' : ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score' : [12.5, 9, 16.5, 15, 9, 20, 14.5, 7, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
}
df = pd.DataFrame(data)
df

attempts       name  score
0         1  Anastasia   12.5
1         3       Dima    9.0
2         2  Katherine   16.5
3         3      James   15.0
4         2      Emily    9.0
5         3    Michael   20.0
6         1    Matthew   14.5
7         1      Laura    7.0
8         2      Kevin    8.0
9         1      Jonas   19.0

In [9]:
moy = (df["attempts"] * df["score"]).sum() / df["attempts"].sum()
print(moy)
result = df[df["score"] > moy]
result["name"]

13.263157894736842


2    Katherine
3        James
5      Michael
6      Matthew
9        Jonas
Name: name, dtype: object